export const CARDS = [
  { name: `The Fool`, unicode: `🃠` },
  { name: `The Magician`, unicode: `🃡` },
  { name: `The High Priestess`, unicode: `🃢` },
  { name: `The Empress`, unicode: `🃣` },
  { name: `The Emperor`, unicode: `🃤` },
  { name: `The Hierophant`, unicode: `🃥` },
  { name: `The Lovers`, unicode: `🃦` },
  { name: `The Chariot`, unicode: `🃧` },
  { name: `Strength`, unicode: `🃨` },
  { name: `The Hermit`, unicode: `🃩` },
  { name: `Wheel of Fortune`, unicode: `🃪` },
  { name: `Justice`, unicode: `🃫` },
  { name: `The Hanged Man`, unicode: `🃬` },
  { name: `Death`, unicode: `🃭` },
  { name: `Temperance`, unicode: `🃮` },
  { name: `The Devil`, unicode: `🃯` },
  { name: `The Tower`, unicode: `🃰` },
  { name: `The Star`, unicode: `🃱` },
  { name: `The Moon`, unicode: `🃲` },
  { name: `The Sun`, unicode: `🃳` },
  { name: `Judgment`, unicode: `🃴` },
  { name: `The World`, unicode: `🃵` },
]
