export const CARDS = [
  { name: `The Fool`, unicode: `🃠`, image: `/media/RWS_Tarot_00_Fool.jpg`, },
  { name: `The Magician`, unicode: `🃡`, image: `/media/RWS_Tarot_01_Magician.jpg`, },
  { name: `The High Priestess`, unicode: `🃢`, image: `/media/RWS_Tarot_02_High_Priestess.jpg`, },
  { name: `The Empress`, unicode: `🃣`, image: `/media/RWS_Tarot_03_Empress.jpg`, },
  { name: `The Emperor`, unicode: `🃤`, image: `/media/RWS_Tarot_04_Emperor.jpg`, },
  { name: `The Hierophant`, unicode: `🃥`, image: `/media/RWS_Tarot_05_Hierophant.jpg`, },
  { name: `The Lovers`, unicode: `🃦`, image: `/media/RWS_Tarot_06_Lovers.jpg`, },
  { name: `The Chariot`, unicode: `🃧`, image: `/media/RWS_Tarot_07_Chariot.jpg`, },
  { name: `Strength`, unicode: `🃨`, image: `/media/RWS_Tarot_08_Strength.jpg`, },
  { name: `The Hermit`, unicode: `🃩`, image: `/media/RWS_Tarot_09_Hermit.jpg`, },
  { name: `Wheel of Fortune`, unicode: `🃪`, image: `/media/RWS_Tarot_10_Wheel_of_Fortune.jpg`, },
  { name: `Justice`, unicode: `🃫`, image: `/media/RWS_Tarot_11_Justice.jpg`, },
  { name: `The Hanged Man`, unicode: `🃬`, image: `/media/RWS_Tarot_12_Hanged_Man.jpg`, },
  { name: `Death`, unicode: `🃭`, image: `/media/RWS_Tarot_13_Death.jpg`, },
  { name: `Temperance`, unicode: `🃮`, image: `/media/RWS_Tarot_14_Temperance.jpg`, },
  { name: `The Devil`, unicode: `🃯`, image: `/media/RWS_Tarot_15_Devil.jpg`, },
  { name: `The Tower`, unicode: `🃰`, image: `/media/RWS_Tarot_16_Tower.jpg`, },
  { name: `The Star`, unicode: `🃱`, image: `/media/RWS_Tarot_17_Star.jpg`, },
  { name: `The Moon`, unicode: `🃲`, image: `/media/RWS_Tarot_18_Moon.jpg`, },
  { name: `The Sun`, unicode: `🃳`, image: `/media/RWS_Tarot_19_Sun.jpg`, },
  { name: `Judgement`, unicode: `🃴`, image: `/media/RWS_Tarot_20_Judgement.jpg`, },
  { name: `The World`, unicode: `🃵`, image: `/media/RWS_Tarot_21_World.jpg`, },
]
