name: Build and Deploy React App to GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build React App
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
      env:
        CI: false

  deploy:
    name: Deploy React App to GitHub Pages
    runs-on: [ubuntu-latest]
    needs: [build]

    steps:
    - uses: actions/checkout@v2
    - uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: build
